project:
  type: website
  output-dir: docs

website:
  title: "Madeline Sands"
  favicon: files/favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume 
      - href: projects.qmd
        text: Projects 
      - href: visualizations.qmd
        text: Visualizations
      - href: nlp.qmd
        text: Natural Language Processing

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



